name: FarmeurimmoPurpurHub
version: '${project.version}'
main: fr.farmeurimmo.purpurhub.PurpurHub
api-version: '1.21'
author: Farmeurimmo
description: PurpurHub
website: https://farmeurimmo.fr
commands:
  build:
    description: Build
    aliases: [ b ]
    permission: purpurhub.build
worlds:
  world:
    generator: FarmeurimmoPurpurHub